# Generated by Django 5.1.6 on 2025-04-14 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test1', models.IntegerField(default=0)),
                ('test2', models.IntegerField(default=0)),
                ('test3', models.IntegerField(default=0)),
                ('test4', models.IntegerField(default=0)),
                ('test5', models.IntegerField(default=0)),
                ('test6', models.IntegerField(default=0)),
                ('test7', models.IntegerField(default=0)),
                ('test8', models.IntegerField(default=0)),
                ('test9', models.IntegerField(default=0)),
                ('test10', models.IntegerField(default=0)),
                ('test11', models.IntegerField(default=0)),
                ('test12', models.IntegerField(default=0)),
                ('test13', models.IntegerField(default=0)),
                ('test14', models.IntegerField(default=0)),
                ('test15', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
