# Generated by Django 5.1.6 on 2025-04-15 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson1', models.BooleanField(default=False)),
                ('lesson2', models.BooleanField(default=False)),
                ('lesson3', models.BooleanField(default=False)),
                ('lesson4', models.BooleanField(default=False)),
                ('lesson5', models.BooleanField(default=False)),
                ('lesson6', models.BooleanField(default=False)),
                ('lesson7', models.BooleanField(default=False)),
                ('lesson8', models.BooleanField(default=False)),
                ('lesson9', models.BooleanField(default=False)),
                ('lesson10', models.BooleanField(default=False)),
                ('lesson11', models.BooleanField(default=False)),
                ('lesson12', models.BooleanField(default=False)),
                ('lesson13', models.BooleanField(default=False)),
                ('lesson14', models.BooleanField(default=False)),
                ('lesson15', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('practice1', models.BooleanField(default=False)),
                ('practice2', models.BooleanField(default=False)),
                ('practice3', models.BooleanField(default=False)),
                ('practice4', models.BooleanField(default=False)),
                ('practice5', models.BooleanField(default=False)),
                ('practice6', models.BooleanField(default=False)),
                ('practice7', models.BooleanField(default=False)),
                ('practice8', models.BooleanField(default=False)),
                ('practice9', models.BooleanField(default=False)),
                ('practice10', models.BooleanField(default=False)),
                ('practice11', models.BooleanField(default=False)),
                ('practice12', models.BooleanField(default=False)),
                ('practice13', models.BooleanField(default=False)),
                ('practice14', models.BooleanField(default=False)),
                ('practice15', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
