# Generated by Django 5.1.6 on 2025-04-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lessonresult_practiceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
